name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]        

    name: PHP ${{ matrix.php }} - Pest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, bcmath
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
          
      - name: Execute tests        
        env:
          WHMCS_URL: "http://localhost"
          WHMCS_API_SECRET: "api-secret"
          WHMCS_API_IDENTIFIER: "api-identifier"
          WHMCS_URL2: "http://localhost"
          WHMCS_API_SECRET2: "api-secret"
          WHMCS_API_IDENTIFIER2: "api-identifier"
        run: vendor/bin/pest
      